# Window decorations will be removed if set to true
remove_decorations = false

# Adds spacing between windows
gap = 5

# How much to increment the master area size.
proportion = 0.1

[keybindings]

# Tile 
tile = "mod4-mod1-t"
untile = "mod4-mod1-u"

# Master Window
make_active_window_master = "mod4-mod1-m"

# Master Number
increase_master = "mod4-mod1-i"
decrease_master = "mod4-mod1-d"

# Cycle Layout
switch_layout = "mod4-mod1-s"

# Next
next_window = "mod4-mod1-n"

# Focus
previous_window = "mod4-mod1-p"

# Master width controls
increment_master = "mod4-mod1-bracketright"
decrement_master = "mod4-mod1-bracketleft"
